### ISSUE TITLE
Persian(fa) translation

### ISSUE THREAD

**Issue by alr86** [uintdev/qrserv#19]
`{
    "@@locale": "fa",
    "page_landing_label": "انتخاب پرونده(ها)",
    "page_landing_msg": "پرونده ها را برای ارسال انتخاب کنید",
    "page_info_noconnection_label": "بدون اتصال شبکه",
    "page_info_noconnection_msg": "به یک شبکه متصل شده و دوباره امتحان کنید",
    "page_info_snapshoterror_label": "خطا",
    "page_info_snapshoterror_msg": "خطا در دریافت اطلاعات شبکه",
    "page_info_fileremoved_label": "پرونده پاک شد",
    "page_info_fileremoved_msg": "پرونده پاک شد",
    "page_info_filemodified_label": "پرونده تغییر یافته",
    "page_info_filemodified_msg": "پرونده تغییر یافته",
    "page_info_permissiondenied_label": "خطا",
    "page_info_permissiondenied_msg": "دسترسی به حافظه رد شد",
    "page_info_insufficientstorage_label": "خطا",
    "page_info_insufficientstorage_msg": "ناکافی حافظه",
    "page_info_portinuse_label": "خطا",
    "page_info_portinuse_msg": "سرور تلاش میکرد با پورتی متصل شود که از قبل مشغول شده بود",
    "page_info_fallback_label": "خطا",
    "page_info_fallback_msg": "خطایی رخ داد.\nCode: ",
    "page_imported_archive_failed": "فایل بایگانی ایجاد نشد: ",
    "page_imported_share_sheet_label": "اشتراک گذاری",
    "page_imported_share_clipboard_label": "هم‌مانند سازی",
    "page_imported_share_clipboard": "هم‌مانند سازی شد",
    "page_imported_fileinpath_enabled": "فعال: نام پرونده در مسیر آن",
    "page_imported_fileinpath_disabled": "غیرفعال: نام پرونده در مسیر آن",
    "page_imported_file": "پرونده",
    "page_imported_size": "اندازه",
    "page_imported_port": "پورت",
    "page_imported_decimalseparator": ".",
    "page_imported_sizesymbol_b": "B",
    "page_imported_sizesymbol_kb": "KB",
    "page_imported_sizesymbol_mb": "MB",
    "page_imported_sizesymbol_gb": "GB",
    "page_imported_sizesymbol_tb": "TB",
    "fab_shutdownserver_label": "خاموش کردن سرور",
    "fab_selectfile_label": "انتخاب پرونده(ها)",
    "info_exception_statusbar": "تغییر رنگ نوار وضعیت ناموفق شد: ",
    "info_exception_navigationbar": "تغییر رنگ نوار ناوبری ناموفق بود: ",
    "info_exception_fileselection_fallback": "انتخاب پرونده(ها) ناموفق شد: ",
    "info_exception_intentstream": "getIntentDataStream خطا: ",
    "info_exception_shutdownfailed": "خاموش کردن سرور ناموفق شد",
    "info_exception_fileremoval": "پاک سازی پرونده های ذخیره در کش ناموفق شد: ",
    "info_exception_portinuse": "خطا در تعریف پورت: ",
    "info_exception_linkopenfailed": "نمیتوان پیوند را باز کرد: ",
    "info_pending_fileprocessing": "در حال پردازش پرونده های انتخابی...",
    "info_pending_fileprocessing_shutdown": "نمیتوان حین پردازش پرونده ها سرور را خاموش کرد",
    "info_pending_servershutdown": "خاموش کردن سرور...",
    "info_pending_appinfo": "بارگذاری...",
    "server_info_tokenmismatch": "عدم تطابق نشان سرور",
    "server_info_shutdownfailed": "خاموش کردن سرور ناموفق شد.کد \nHTTP: ",
    "server_info_gone": "سرور از بین رفته است: ",
    "info_title": "درباره...",
    "info_packageinfofail": "خطا",
    "info_opensource_title": "متن باز",
    "info_donate_title": "حمایت",
    "info_close": "بستن",
    "dam_state_enabled": "فعال: حالت دسترسی مستقیم",
    "dam_state_disabled": "غیرفعال: حالت دسترسی مستقیم",
    "dam_path_not_found": "خطا: مسیر حالت دسترسی مستقیم پیدا نشد"
}`

**Comment by uintdev** [comment]
Surprisingly, the app appeared to have handled the RTL (right to left) text direction appropriately.. for the most part. I had to force some LTR (left to right) text direction on information where RTL would make it look very off or broken (such as file paths, file names, and URLs).
It does appear that URLs can look slightly broken in Android's share sheet but copying it to the clipboard or sharing would have it the text exactly how it should be laid out. But that's the Android team's problem that may or may not ever get fixed. 

Now that had been handled, I'm going to prepare the release. Coming not too long from now...

**Comment by uintdev** [comment]
Included as of v2.3.2.

**Comment by alr86** [comment]
I got the latest version of the software and works properly, thank you for responding to less than 24 hours😁
