### ISSUE TITLE
No port on main screen

### ISSUE THREAD

**Issue by Kiwoth** [uintdev/qrserv#3]
I can't seen to find any label that reflects the actual port on the main screen. I think it should be somewhere.

**Comment by uintdev** [comment]
On the device I mainly test on, this would show up in the sharesheet  with a full URL. Although, I believe some devices may not have such information displayed there and so would require extra steps just to know the port number in use.

I had just released v1.3.0, which will display the port number below the file size. This will be up on the Play Store as soon as it passes review.

**Comment by Kiwoth** [comment]
Working like a charm!
