### ISSUE TITLE
Add the light theme

### ISSUE THREAD

**Issue by xmha97** [uintdev/qrserv#6]
Thanks for this app.
Please add the light theme.

**Comment by uintdev** [comment]
I had been looking into how the app should be themed in v2.0.0. While I did see a promising way of getting both dark and light theme with some nice little Material 3 touches in the UI, it looks like I have to redo parts of the UI for things to be themed properly.. and still wait a while where Material 3 theming is very much incomplete. Not so much I can do in that case, and I don't want to release a version of the app that has poor visibility in places, let alone look very off in places.

I could put together a light theme that is shown based on the system theme. I think that would be fine enough while I wait for Material 3 theming to fill in the remaining gaps for a future change of UI.

**Comment by xmha97** [comment]
Great 👍

**Comment by uintdev** [comment]
I decided to go by the light and dark theme according to the 'about' dialogue box theme. Should look far more consistent.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by uintdev** [comment]
Added as of v2.1.0. Before closing this one up, I'd like your feedback on if the light theme looks alright in the new release.

**Comment by uintdev** [comment]
Closing as resolved.
