### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by xmha97** [uintdev/qrserv#7]
I want to use this app on the table.
Please add support landscape mode.

**Comment by uintdev** [comment]
The possibility _might_ be there. I'll take a look into it. I don't have a physical tablet to test with, so I suppose an Android emulator will suffice.
Please note that if there is a solution for this that there are no plans to adjust the UI itself in any way to be more suitable for tablets, as this was mainly designed to be used on mobile displays.

**Comment by xmha97** [comment]
OK, thanks for supporting...

**Comment by uintdev** [comment]
Without making a dedicated tablet build (normally would be fine with app bundle [used for Play Store] but APK files are also used so rather not have even more of those), the rotation has to be set on app launch. This is not ideal, as that means for a moment it could go portrait on a tablet (but then allow control by sensor) or look a bit weird for a second if on landscape from a previous app and then launch the app on mobile (i.e. using the sharesheet in the photos app while in landscape and then selecting this app). But despite all that and a slightly stretched UI in places, it should do the trick.

Lining this one up for the next release.

**Comment by xmha97** [comment]
Thanks.

**Comment by uintdev** [comment]
Change made as of the new v2.1.0 release. Please do let me know if this works in your case.

**Comment by uintdev** [comment]
Closing as resolved.

**Comment by uintdev** [comment]
> On my phone, this mode does not work.

This is only enabled for tablets, as the UI will look very off with how little space there would be while in landscape on phones.
