### ISSUE TITLE
the ability to send many files

### ISSUE THREAD

**Issue by Wjxfi** [uintdev/qrserv#9]
1 little

all other applications similar to this can already send a lot of files

For example localsend

**Comment by uintdev** [comment]
This can be done by selecting multiple files through the files / documents UI app (shown when pressing on the floating action button in the app) by press and holding on one file at first or making such multi-selection in an app such as Google Photos and then sharing via QRServ. This would be made into a ZIP archive that can then be downloaded.

**Comment by uintdev** [comment]
The functionality used for creating an archive file does not offer the option to add to an existing archive file, so I'm afraid that wouldn't be possible with how that is.
